### ISSUE TITLE
non-`master` branches in index unsupported by `cargo`

### ISSUE THREAD

**Issue by yodaldevoid** [moriturus/ktra#16]
`cargo` at the moment does not support indexes with a main branch as anything other than `master`. See https://github.com/rust-lang/cargo/pull/4024 for the PR that forced this and https://github.com/rust-lang/cargo/issues/7329 for an issue tracking support for other branches.

`ktra`'s default branch is currently `main` and it makes it seem like `main` will work as a main branch for an index in it's documentation. Until `cargo` adds support, I think `ktra` should change it's default branch and all references in the documentation to `master` to avoid difficulty when a user is trying to set up a new registry.

**Comment by vojtechkral** [comment]
This has been fixed in cargo, these days it handles the `main` branch just fine.
This issue can be closed...

**Comment by gagbo** [comment]
Hello,

In any case, the branch name used in the registry is now a configuration option. So if there is still the cargo issue (I didn't test sorry), we'll make a change to moriturus/ktra-book to mark it in the documentation

**Comment by vojtechkral** [comment]
I tested with `main` and it simply works, cargo has no complaints :)
