### ISSUE TITLE
No push to remote repo

### ISSUE THREAD

**Issue by ebioman** [moriturus/ktra#34]
Hi
Thanks for this great repo! I am running into some - what I guess- basic issues.
I managed to run locally ktra, add my user and initialize with a gitlab repo as described in the book.
As well the configuration step and pushing a project into the index works - almost.

```bash
cargo publish --allow-dirty --token --TOKEN--
Updating `http://gitlab.ngs-ai.lab/eschmid/crate_ngsai/` index
Compiling abc v0.2.3 (/home/eschmid/Projects/AgnosticBamCounter/target/package/abc-0.2.3)
    Finished dev [unoptimized + debuginfo] target(s) in 35.39s
   Uploading abc v0.2.3 (/home/eschmid/Projects/AgnosticBamCounter)
```
So that looks good to me and the ktra index/repo reflects as well this new addition.
What is though unexpected, is that the gitlab did not receive any commit, pushes - nada.

Any idea what prevents the proper push - but no error message at all ?

## Update

Sorry just to add, if I try then to add the above as a dependency for an empty project, I get

```bash
cargo build
    Updating `http://gitlab.ngs-ai.lab/eschmid/crate_ngsai/` index
error: no matching package named `abc` found
location searched: registry `http://gitlab.ngs-ai.lab/eschmid/crate_ngsai/`
required by package `goo v0.1.0 (/home/eschmid/Projects/goo)`
```

So it checks in the right place, but obviously the index contains nothing because the above step only did local index changes but did not push to the remove repo

**Comment by jbeaurivage** [comment]
Looks like your issue is related to #20

**Comment by ebioman** [comment]
I think the problem was that I established the GitHub page without the json initially. When I tried then later it would obviously fail and I add the json file 
Afterwards the described issue appeared. I think it might be a problem of order as deleting everything and repeating the steps in the proper order fixed the issue now
