### ISSUE TITLE
Changing branch

### ISSUE THREAD

**Issue by tafia** [moriturus/ktra#5]
First thank you for this project, this is awesome!

I had one issue though that I managed to fixed but I am opening the issue in case someone else has it too.

I am not using github so default branch name is not `main` but `master` (in my case it was bitbucket, fyi).

I found that you could change the branch name in `ktra.toml` file:
```toml
[index_config]
remote_url = "..."
branch = "master"
```

 ... but if you do it AFTER the first initialization, then you get stuck with git error:
```
src refspec 'refs/heads/master' does not match any existing object
```

The solution I found was to delete all existing artifacts (db, index and crates directories) before starting ktra again with the updated config.

Now it works like a charm!

**Comment by moriturus** [comment]
Thank you for using Ktra and opening issue!
I'll document about branch names in the next release.

**Comment by moriturus** [comment]
I wrote a document about the branch in `0.4.2` release.
Feel free to reopen this issue if you think it is insufficient.
