### ISSUE TITLE
[Feat Req] crates.io mirroring

### ISSUE THREAD

**Issue by Geobert** [moriturus/ktra#8]
When setting up ktra as the default registry, if a crate is not found, get it from crates.io and cache it in ktra. 

My company is looking for a solution to allow offline build from our CI servers and atm, only Meuse is capable of that but written in Clojure, which limit our capability to contribute back as none of us knows Clojure 😅

**Comment by moriturus** [comment]
Hi @Geobert, thank you for your feature request!

Your proposal is really interesting to me and I couldn't come up with that without your opinion.  
I cannot say when exactly, but I will try to implement that feature.

**Comment by Geobert** [comment]
Here is how Meuse is doing it: https://meuse.mcorbin.fr/installation/mirroring/

**Comment by moriturus** [comment]
Implemented at 0.5.0.  
If you have any problems about this new feature, feel free to reopen this issue.
