### ISSUE TITLE
[Question] Does ktra needs write access to index repository?

### ISSUE THREAD

**Issue by Geobert** [moriturus/ktra#9]
Hi!

We are on the verge to install Ktra in my workplace and I'm reading the Ktra book on the procedure (thanks for writing it!).

I have a couple of questions though:
- Why is `config.json` refering to localhost? 
- Does the user/password to the index needs write access to the index repository?

Thank you for your help!

**Comment by moriturus** [comment]
Hi @Geobert.

1. The book is written to build up a ktra server on readers' `localhost` so `cofig.json` refers to `localhost`.  
Of course you can choose one and use any domains or global/local IP addresses you have.

2. **Yes**. ktra commit and push to the index repository every time when your crate is registered.

**Comment by Geobert** [comment]
Thank you for your answers! :D
